In [1]:
import numpy as np
import pandas as pd
#from sklearn import linear model
from sklearn.model_selection import train_test_split,KFold, cross_val_score, cross_val_predict
from matplotlib import pyplot as plt
from sklearn import metrics
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.linear_model import  LinearRegression, Ridge, Lasso, RidgeCV, LassoCV

In [2]:
df=pd.read_csv("houses_train.csv")
df

Unnamed: 0     price       condition          district  max_floor  \
0           5546  130000.0  newly repaired            Center          4   
1           2979   65000.0            good           Arabkir          5   
2           2698  129000.0            good            Center         10   
3           4548   52000.0  newly repaired            Center         14   
4           2982   65000.0  newly repaired            Center         12   
...          ...       ...             ...               ...        ...   
4995        2417   56000.0            good         Davtashen         16   
4996        1307  115000.0            good           Arabkir          6   
4997        2863  127000.0  newly repaired            Center          9   
4998        1470   41800.0            good            Center          5   
4999        1272   36000.0            good  Malatia-Sebastia         14   

                    street  num_rooms   region   area  \
0           Sayat Nova Ave          3  Yerevan   96.0   
1             Hr.Kochar St          3  Yerevan   78.0   
2          M.Khorenatsi St          3  Yerevan   90.0   
3              Argishti St          2  Yerevan   53.0   
4             Mashtots Ave          2  Yerevan   47.0   
...                    ...        ...      ...    ...   
4995  Davtashen 3 district          3  Yerevan  100.0   
4996             Adonts St          3  Yerevan  135.0   
4997          Yekmalyan St          3  Yerevan   73.0   
4998      D. Demirchyan St          1  Yerevan   48.0   
4999         Z.Andranik St          3  Yerevan   96.0   

                                                    url  num_bathrooms  \
0     http://www.myrealty.am/en/item/28244/3-senyaka...              1   
1     http://www.myrealty.am/en/item/18029/3-senyaka...              1   
2     http://www.myrealty.am/en/item/37797/3-senyaka...              1   
3     http://www.myrealty.am/en/item/36153/2-senyaka...              1   
4     http://www.myrealty.am/en/item/17566/2-senyaka...              1   
...                                                 ...            ...   
4995  http://www.myrealty.am/en/item/30305/3-senyaka...              1   
4996  http://www.myrealty.am/en/item/4118/3-senyakan...              1   
4997  http://www.myrealty.am/en/item/32305/3-senyaka...              2   
4998  http://www.myrealty.am/en/item/34952/1-senyaka...              1   
4999  http://www.myrealty.am/en/item/38050/3-senyaka...              1   

     building_type  floor  ceiling_height  
0            stone      3             3.2  
1            stone      2             2.8  
2            panel      3             2.8  
3          monolit      5             3.0  
4            panel      3             2.8  
...            ...    ...             ...  
4995         panel      8             2.8  
4996         stone      5             2.8  
4997       monolit      3             3.0  
4998         stone      1             2.8  
4999         panel     14             2.8  

[5000 rows x 14 columns]

In [4]:
df['Unnamed: 0'].nunique()

5000

In [5]:
df['region'].unique()

array(['Yerevan'], dtype=object)

In [6]:
df['street'].value_counts()

Komitas Ave                   255
Mashtots Ave                  147
Tsarav Aghbyur St             113
Sayat Nova Ave                113
Mamikoniants St               106
                             ... 
H. Shahinyan St                 1
Avetisyan 4 St                  1
Sevqareci Saqo St               1
Tigran Mets Ave 2 alley         1
Verin Shengavit 2th street      1
Name: street, Length: 336, dtype: int64

In [7]:
y=df['price']
y[:5]

0    130000.0
1     65000.0
2    129000.0
3     52000.0
4     65000.0
Name: price, dtype: float64

In [8]:
X=df.drop(['Unnamed: 0','price','street','region','url'], axis=1)
X.head()

condition district  max_floor  num_rooms  area  num_bathrooms  \
0  newly repaired   Center          4          3  96.0              1   
1            good  Arabkir          5          3  78.0              1   
2            good   Center         10          3  90.0              1   
3  newly repaired   Center         14          2  53.0              1   
4  newly repaired   Center         12          2  47.0              1   

  building_type  floor  ceiling_height  
0         stone      3             3.2  
1         stone      2             2.8  
2         panel      3             2.8  
3       monolit      5             3.0  
4         panel      3             2.8

In [8]:
X['district'].value_counts()

Center              2086
Arabkir             1320
Avan                 252
Malatia-Sebastia     235
Davtashen            235
Nor Norq             233
Qanaqer-Zeytun       201
Achapnyak            192
Shengavit            163
Erebuni               75
Norq Marash            5
Vahagni district       2
Nubarashen             1
Name: district, dtype: int64

In [9]:
X=pd.get_dummies(X)
X

max_floor  num_rooms   area  num_bathrooms  floor  ceiling_height  \
0             4          3   96.0              1      3             3.2   
1             5          3   78.0              1      2             2.8   
2            10          3   90.0              1      3             2.8   
3            14          2   53.0              1      5             3.0   
4            12          2   47.0              1      3             2.8   
...         ...        ...    ...            ...    ...             ...   
4995         16          3  100.0              1      8             2.8   
4996          6          3  135.0              1      5             2.8   
4997          9          3   73.0              2      3             3.0   
4998          5          1   48.0              1      1             2.8   
4999         14          3   96.0              1     14             2.8   

      condition_good  condition_newly repaired  condition_zero condition  \
0                  0                         1                         0   
1                  1                         0                         0   
2                  1                         0                         0   
3                  0                         1                         0   
4                  0                         1                         0   
...              ...                       ...                       ...   
4995               1                         0                         0   
4996               1                         0                         0   
4997               0                         1                         0   
4998               1                         0                         0   
4999               1                         0                         0   

      district_Achapnyak  ...  district_Nor Norq  district_Norq Marash  \
0                      0  ...                  0                     0   
1                      0  ...                  0                     0   
2                      0  ...                  0                     0   
3                      0  ...                  0                     0   
4                      0  ...                  0                     0   
...                  ...  ...                ...                   ...   
4995                   0  ...                  0                     0   
4996                   0  ...                  0                     0   
4997                   0  ...                  0                     0   
4998                   0  ...                  0                     0   
4999                   0  ...                  0                     0   

      district_Nubarashen  district_Qanaqer-Zeytun  district_Shengavit  \
0                       0                        0                   0   
1                       0                        0                   0   
2                       0                        0                   0   
3                       0                        0                   0   
4                       0                        0                   0   
...                   ...                      ...                 ...   
4995                    0                        0                   0   
4996                    0                        0                   0   
4997                    0                        0                   0   
4998                    0                        0                   0   
4999                    0                        0                   0   

      district_Vahagni district  building_type_monolit  building_type_other  \
0                             0                      0                    0   
1                             0                      0                    0   
2                             0                      0                    0   
3                             0                      1                    0   
4                  

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=5)
lm = LinearRegression()
lm.fit(X_train, y_train)
lm.coef_, lm.intercept_

(array([   -42.30629329,  -6028.16911612,   1194.67381652,  12616.35819783,
           -40.11774834,  22449.92791106,   2034.72462281,  13546.99094576,
        -15581.71556857,  -8737.81184203,  10540.45633667, -12562.00971985,
         38646.8214121 ,  -1601.89634365,  -6253.83041371,  -9180.75325931,
         -7009.36148149,  28947.48702584, -19491.36650626,   -894.92227936,
         -8995.02407667,  -3407.78885227,  12758.70328651,   1086.85188885,
        -11526.14928092,  -2319.40589444]),
 -96900.30502567373)

In [11]:
preds=lm.predict(X_test)
preds

array([182864.97614466,  72042.74422895, 122207.36134184,  53856.0130326 ,
        90030.22065607, 136382.7691386 ,  96286.60252197,  60616.93066151,
       109720.88518081, 182188.03978883,  59920.85278522,  62974.73968713,
        44674.84651613, 153015.43208326,  59920.85278522, 112742.70004663,
        42830.4298305 ,  56580.26402839,  95963.47199031,  90566.2833091 ,
        43182.4776311 , 134895.20085655,   4709.57955603,  98372.55818595,
        57938.60161718,  49120.37140586,  86050.60614629,  53395.85520447,
       133385.75681704, 101988.24277774,  93796.06841311, 191125.74325899,
       103350.82309883,  80941.59900318,  73359.32254764,  53262.23406373,
        95991.0959984 ,  22371.74687685, 151856.54017483, 163064.7890485 ,
        71582.83692359,  97672.80920214,  33470.5872852 ,  21504.92170961,
        30775.00458444,  88122.13564253,  64075.47453395, 108072.86969379,
        80616.72722803,  82033.69784814, 162957.0957064 , 196657.17958039,
        44014.08782696,  

In [12]:
print(np.sqrt(mean_squared_error(y_train, lm.predict(X_train))))
print(np.sqrt(mean_squared_error(y_test, lm.predict(X_test))))

29318.623156259087
28738.824115001382


## Ridge regression 

In [13]:
rr=Ridge(alpha=13)
rr.fit(X_train,y_train)
rr.coef_, rr.intercept_

(array([-3.94030048e+01, -6.17848485e+03,  1.20283087e+03,  1.27241949e+04,
        -3.81431427e+01,  1.91415389e+04,  1.64810399e+03,  1.33286010e+04,
        -1.49767050e+04, -8.38393148e+03,  1.00967520e+04, -1.19295689e+04,
         3.81453950e+04, -1.72261683e+03, -5.44833052e+03, -8.90345872e+03,
        -6.89444249e+03,  6.69276259e+03, -1.44555305e+03, -1.20222104e+03,
        -8.54119378e+03, -4.63592713e+02,  1.26674767e+04,  1.01388915e+03,
        -1.16953210e+04, -1.98604489e+03]),
 -87322.93984987895)

In [14]:
rr.predict(X_test)

array([182418.50030399,  72226.38624672, 121397.17039929,  54473.5097793 ,
        89880.11178517, 136156.93237044,  96162.52798939,  61416.20373027,
       109497.08280313, 182201.56574759,  59919.31763004,  62788.64347916,
        44889.93727053, 152836.17160164,  59919.31763004, 111975.7372321 ,
        43022.39169759,  57384.23515798,  95856.12298595,  90740.42645261,
        43292.65718191, 134192.61209144,   4669.06910256,  97458.98667805,
        57640.07647918,  49890.74886385,  84894.37712096,  54314.57695255,
       133379.3292039 , 102570.24139223,  94077.39371219, 190684.5808811 ,
       103410.26656209,  80828.52150429,  73057.24897281,  53044.29955062,
        95769.33863161,  22298.34880688, 151628.1432994 , 162521.01892848,
        71966.61883142,  98941.13363268,  34204.59340835,  22481.68809638,
        31923.02392096,  88170.43421341,  63817.35657064, 108038.26410563,
        80809.37087613,  81684.15346307, 163056.91156333, 196396.5289793 ,
        43990.66995366,  

In [15]:
print(np.sqrt(mean_squared_error(y_train, rr.predict(X_train))))
print(np.sqrt(mean_squared_error(y_test, rr.predict(X_test))))

29334.969321665438
28702.61756437077


## Lasso Regression

In [16]:
lr=Lasso(alpha=13)
lr.fit(X_train,y_train)
lr.coef_, lr.intercept_

(array([-3.44549581e+01, -6.04882958e+03,  1.19669035e+03,  1.26805644e+04,
        -4.20101352e+01,  2.17246917e+04,  0.00000000e+00,  1.15470166e+04,
        -1.73771052e+04, -2.06075537e+03,  1.68189720e+04, -5.93090413e+03,
         4.49695190e+04,  4.46670213e+03,  0.00000000e+00, -2.59057845e+03,
        -4.04986464e+02,  2.22199670e+04, -0.00000000e+00,  5.10106304e+03,
        -2.28525321e+03,  0.00000000e+00,  1.48645958e+04,  3.10137522e+03,
        -9.38943482e+03, -3.23102486e+01]),
 -101566.67162769902)

In [17]:
rr.predict(X_test)

array([182418.50030399,  72226.38624672, 121397.17039929,  54473.5097793 ,
        89880.11178517, 136156.93237044,  96162.52798939,  61416.20373027,
       109497.08280313, 182201.56574759,  59919.31763004,  62788.64347916,
        44889.93727053, 152836.17160164,  59919.31763004, 111975.7372321 ,
        43022.39169759,  57384.23515798,  95856.12298595,  90740.42645261,
        43292.65718191, 134192.61209144,   4669.06910256,  97458.98667805,
        57640.07647918,  49890.74886385,  84894.37712096,  54314.57695255,
       133379.3292039 , 102570.24139223,  94077.39371219, 190684.5808811 ,
       103410.26656209,  80828.52150429,  73057.24897281,  53044.29955062,
        95769.33863161,  22298.34880688, 151628.1432994 , 162521.01892848,
        71966.61883142,  98941.13363268,  34204.59340835,  22481.68809638,
        31923.02392096,  88170.43421341,  63817.35657064, 108038.26410563,
        80809.37087613,  81684.15346307, 163056.91156333, 196396.5289793 ,
        43990.66995366,  

In [18]:
print(np.sqrt(mean_squared_error(y_train, lr.predict(X_train))))
print(np.sqrt(mean_squared_error(y_test, lr.predict(X_test))))

29323.08695868943
28711.634856424538


## Cross-validation + Ridge Regression with automatically calculated alpha

In [19]:
ridge = RidgeCV(normalize=True, scoring = 'neg_mean_squared_error', cv=10)

In [20]:
scores = cross_val_score(ridge, X, y,scoring = 'neg_mean_squared_error', cv=10)
np.mean(np.sqrt(np.abs(scores)))

29500.696359180165

In [21]:
predictions = cross_val_predict(ridge, X, y, cv=10)
predictions

array([131557.71168284,  64415.98708386,  94328.13068291, ...,
       133549.23939678,  65512.31804912,  55082.2378112 ])

### Cross-validation + Ridge Regression without cross_val_predict

In [22]:
kf = KFold(n_splits=10)
kf.get_n_splits(X)

10

In [23]:
RMSE_test=[]
RMSE_train=[]
for tr_index, ts_index in kf.split(X):
    X_tr, X_ts = X.iloc[tr_index], X.iloc[ts_index]
    y_tr, y_ts = y[tr_index], y[ts_index]
    rr_cv=Ridge(0.01)
    rr_cv.fit(X_tr,y_tr)
    preds_tr=rr_cv.predict(X_tr)
    preds_ts=rr_cv.predict(X_ts)
    RMSE_test.append(float(np.sqrt(mean_squared_error(preds_ts, y_ts))))
    RMSE_train.append(float(np.sqrt(mean_squared_error(preds_tr, y_tr))))
#print ('Test RMSE:', RMSE_test)
#print ('Train RMSE:', RMSE_train)
print("Mean train RMSE(Ridge regression):", sum(RMSE_train)/len(RMSE_train))
print("Mean test RMSE(Ridge regression):", sum(RMSE_test)/len(RMSE_test))

Mean train RMSE(Ridge regression): 29186.116494366997
Mean test RMSE(Ridge regression): 29255.62628371615


### Cross-validation + Ridge

In [24]:
r=Ridge(alpha=0.01)
scores_rg=cross_val_score(r,X,y, scoring = 'neg_mean_squared_error',cv=10)
print('Lasso scores:', scores_rg)
y_rg=cross_val_predict(r, X, y, cv=10)
print('Predictions:', y_rg)
RMSE_mean_Ridge=np.mean(np.sqrt(np.abs(scores_rg)))
print("Mean RMSE(Ridge regression):", RMSE_mean_Ridge)

Lasso scores: [-8.74678883e+08 -8.57675856e+08 -9.60224260e+08 -8.95548981e+08
 -9.37678278e+08 -8.47763079e+08 -7.72735463e+08 -6.67143109e+08
 -1.06291323e+09 -7.19016941e+08]
Predictions: [134509.12666258  62856.13223245  96497.94321309 ... 129555.45947057
  67833.22134519  56198.76177204]
Mean RMSE(Ridge regression): 29255.62628371615


### Cross-validation + Lasso

In [29]:
lasso=Lasso(alpha=0.3, max_iter=100000)
scores_ls=cross_val_score(lasso,X,y, scoring = 'neg_mean_squared_error',cv=10)
print('Lasso scores:', scores_ls)
y_ls=cross_val_predict(lasso, X, y, cv=10)
print('Predictions:', y_ls)

Lasso scores: [-8.74716101e+08 -8.57689435e+08 -9.59745550e+08 -8.95532964e+08
 -9.37678091e+08 -8.47787496e+08 -7.72778585e+08 -6.67069623e+08
 -1.06292278e+09 -7.18989531e+08]
Predictions: [134505.90941423  62855.93217481  96497.63471523 ... 129554.93497444
  67834.6443328   56204.01199738]


In [30]:
RMSE_mean_Lasso=np.mean(np.sqrt(np.abs(scores_ls)))
print("Mean RMSE(Lasso regression):", RMSE_mean_Lasso)

Mean RMSE(Lasso regression): 29254.853578379767


##### The best model I get with Lasso regression(+cross validation).